id: P3AA52AEC
initial_creation_type: ocr
source_metadata:
  volumes:
    84d58056f1f749fa89fe0de918cc0e1a:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ཞིབ་མོ་རྣམ་པར་འཐག་པ་ཞེས་བྱ་བའི་མདོ།
      total_pages: 1605
      volume_number: 57
